### ISSUE TITLE
Simulation didn't work, likely because other Lua extensions were already installed

### ISSUE THREAD

**Issue by MrLennyn** [nameouschangey/STORMWORKS_VSCodeExtension#10]
![image](https://user-images.githubusercontent.com/87110361/145134227-ea2ae572-9e85-4c10-9da1-24775490f5db.png)

I had installed _lua-debug extension_ by actboy169 and _lua language server extension_ by sumneko, both used by this extension, months before installing _Stormworks Lua with LifeBoatAPI_. I believe having them already installed was causing the error we see above, but I'm not able to reproduce the issue after solving it. 

**My solution:** Uninstalling all three extensions and reinstalling _Stormworks Lua with LifeBoatAPI_.

Also, I love this thing. Good job.

**Comment by nameouschangey** [comment]
Ah thanks for raising this!

I'm not sure what exactly's causing that - but I've got an idea for a fix, that would at least allow the Simulator to run unimpeded (it may still have trouble with intellisense though).

I'm glad reinstalling worked for you though this time.

**Comment by nameouschangey** [comment]
I'm closing this, as I *hope* it's fixed in latest.

Unfortunately, extremely hard to test realistically. But if it's relating to the settings not being updated properly, I've changed how cpath and path are set for the debugger - and it may avoid this problem.

If anybody comes across this again, please don't hesitate to resubmit with new info.
