### ISSUE TITLE
minizer makes wrong variable names

### ISSUE THREAD

**Issue by samohtGTO** [nameouschangey/Stormworks_VSCodeExtension#102]
**What I expected to happen**
i expect that the minizer shorten all variables and globals etc.

**What happened instead**
so the minimizer makes in some files the mistake of making a variable the wrong name so later when probaly the right name of that var becomes undefined

**How do I reproduce this?**
Reliable steps that should produce this issue:
1. make a file use the pid thing from the lib doesnt matter wich lib you use the pid thing from
2. make a basic thing there is a example in the /lib/pid/pid.lua to see how it kinda work and in the other lib is argument explained
3. build the file

**Screenshots and Project zip file**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/71775252/183380777-1f3fd56d-a354-4391-aab0-e2502a69921b.png">
screenshot +plus zip of the project
https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/9280458/coaltest.2.zip
**Additional info**
i have no additional info

**Comment by samohtGTO** [comment]
whoops use the wrong zip
[coaltest (2).zip](https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/9280458/coaltest.2.zip)

**Comment by nameouschangey** [comment]
This is a code error on your side I'm afraid.
In your Maths utils (possibly other files too) - you've got:
` ---@section pid 2 pidclass`
but then just `---@endsection` at the bottom

Because you've named the section "pidclass" your endsection must match, e.g. `---@endsection pidclass`
You'll want to fix all errors similar to that.

Closing this as rejected.
