### ISSUE TITLE
Minifier error

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [nameouschangey/STORMWORKS_VSCodeExtension#57]
The minifier errors every time I press F7.
Error that it shows:
![image](https://user-images.githubusercontent.com/57036815/150574474-3c3e04c0-2f04-4451-a870-74e881069339.png)

**Comment by nameouschangey** [comment]
This is fixed in the current patch, apologies for the frustration till it releases.

if you delete that `predictedBoilerplateSize` from `tostring(sizeWithoutBoilerplate + predictedBoilerplateSize)` you'll be able to keep working till the patch comes out. (or implement the actual fix itself, there's a missing `or 0` from where `predictedBoilerplateSize` gets assigned)

Thanks for raising this.
