### ISSUE TITLE
More minimzation

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [nameouschangey/STORMWORKS_VSCodeExtension#65]
It would be really nice to see more minimization, specifically, I'd like to minimize my code to a 1 liner which Pony's IDE already does and it would be really nice to see it in this extension as well!

Maybe it could be assigned to another hotkey, my main use case for it would be to minimize my code so much that no one else can read it and modify it. Kind of like an anti-piracy feature.

UPDATE: It would be really cool to have a minimization system like in Pony's IDE.
Meaning there would be 2 different modes:

- Conservative
    Will only replace names of declared variables and functions.
- Aggressive
    Will replace almost every variable and function name.

I'd very much like to use the aggressive function for minimizing my code but Pony's IDE doesn't have support for the new functions in addon Lua so I'm forced to use the conservative mode.

I'd also like to mention that I'm facing some issues with the already existing minimization in your extension. In-game Lua does not like the function lines at all for some reason and I can't figure out why.
![image](https://user-images.githubusercontent.com/57036815/153632019-4faff487-9624-4756-a90b-eaee752086ec.png)

**Comment by nameouschangey** [comment]
In terms of "more minification", if you have specific optimizations in mind - please share, I'm happy to improve it.
But as it is, it currently reduces a lot further than PonyIDE or LuaMin are capable of - and so, I'm not sure there are many more easy wins to be made.

In terms of it being a one-liner for obfuscation, generally I don't really see the point in it. The code you're left with will 9/10 times be near unreadable if it does anything of much complexity. If you like it to be one-line, perhaps you could replace all \n with spaces, as a post-build action in the _buildactions.lua file?
But given this is an open source project, I'm not specifically expending effort to help somebody else close their source.

For the agressive vs. conservative mode, every minification is already configurable. You can either set it in the _buildactions.lua via the MinifierParams object or as a VSCode setting in the project.

For the last point, I believe the issue is the docs for addons are now particularly out of date. I can only apologies for that - but there's a setting in the extension if you want to provide a more up to date version of the Nelo docs files by Rene Sackers (or your own equivilent).
But for addon development, I'd also tend to recommend turning of most of the minifications as size doesn't matter.
I will get them up to date at _some point_ but if you're actively making addons I wouldn't wait for me; as it could be some time.
If you think it's more than just missing some functions from the addon intellisense though - let me know, and upload a zip of your project + the expected behaviour and I can try to reproduce it.

Many Thanks,
Gordon

**Comment by THE-SIMPLE-MARK** [comment]
Thanks for replying! Your answer helped a lot, I don't think I have any other questions now. (By the way, I'm not trying to close off my source completely, I just don't want my code to be fully visible in SW, it already has its own repository where I'll have the full code.)

**Comment by nameouschangey** [comment]
Gotcha - prefer people look at the *real* source/where they can contribute/follow etc. - than take snippets out of context/try to faff with something they shouldn't be.

Glad it helped though - apologies the addon API stuff is outdated currently.
