### ISSUE TITLE
SimulatorConfig - Portrait Mode Isn't Working

### ISSUE THREAD

**Issue by Dealman** [nameouschangey/STORMWORKS_VSCodeExtension#7]
`configureScreen` has an optional parameter for setting whether or not the screen is meant to be rendered as portrait mode. This parameter is seemingly ignored or not working as intended, whether it's set to `true` or `false`. It will always start in landscape mode.

Manually checking the Portrait checkbox works as intended, however.

This is for V0.0.4

**Comment by nameouschangey** [comment]
Thanks for raising this!

**Comment by nameouschangey** [comment]
Fixed, will be released in next update (likely by end of week)

This was actually a great catch; it turns out it wasn't just that it wasn't setting the portrait mode - it was a mistake that had gone into all messages that were being sent, that fortunately, only showed up on this one specific command. But who knows what else it could have been affecting if it was left there.

Thanks!
